spring:
  application:
    name: air-intelligence
  data:
    mongodb:
      uri: mongodb://localhost:27017/dust_mongo

web-push:
  vapid:
    public-key: ${VAPID_PUBLIC_KEY}
    private-key: ${VAPID_PRIVATE_KEY}

cookie:
    domain: ${COOKIE_DOMAIN:localhost}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173}

api:
  fast-api-url: ${FAST_API_URL}

server:
  forward-headers-strategy: framework
