name: Gradle Build and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. JDK 21 설치
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      # 3. gradlew 실행권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 4. 테스트 제외 빌드
      - name: Build without tests
        run: ./gradlew clean build -x test

      # 5. JAR 파일 복사 (app.jar로 고정)
      - name: Copy JAR
        run: cp build/libs/*.jar app.jar

      # 6. DockerHub 로그인
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 7. Docker Image Build & Push
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/air-core-dev-be-images:latest

      # 8. 서버 접속해서 docker compose 재배포
      - name: SSH and deploy with docker compose
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.GCE_HOST }}
          username: ${{ secrets.GCE_USER }}
          key: ${{ secrets.GCE_SSH_KEY }}
          script: |
            cd /home/ubuntu/rowing/springboot
            docker compose down || true
            docker compose pull
            docker compose up -d
            docker compose ps
