name: Gradle Build and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build without tests
        run: ./gradlew clean build -x test

      # 빌드 결과 파일명 추출
      - name: Find built JAR name
        id: findjar
        run: |
          JAR_PATH=$(ls build/libs/*-SNAPSHOT.jar | head -n 1)
          echo "JAR_PATH=$JAR_PATH" >> $GITHUB_ENV
          echo "📦 Found JAR: $JAR_PATH"

      # 원격 폴더 초기화 및 JAR 복사
      - name: Copy JAR to GCP VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.GCE_HOST }}
          username: ${{ secrets.GCE_USER }}
          key: ${{ secrets.GCE_SSH_KEY }}
          source: ${{ env.JAR_PATH }}
          target: "/home/ubuntu/rowing/springboot/app.jar"
          strip_components: 2

      - name: SSH and deploy with docker compose
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.GCE_HOST }}
          username: ${{ secrets.GCE_USER }}
          key: ${{ secrets.GCE_SSH_KEY }}
          script: |
            cd /home/ubuntu/rowing/springboot
            [ -d app.jar ] && rm -rf app.jar
            docker compose down || true
            docker compose build --no-cache
            docker compose up -d
